# Generated by Django 3.1.6 on 2021-10-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210309_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'f'), ('MALE', 'm'), ('NONBINARY', 'n')], default='n', max_length=10),
        ),
    ]
